export const PAGE_CREATE_SUCCESS = 'PAGE_CREATE_SUCCESS'
export const PAGE_CREATE_FAIL = 'PAGE_CREATE_FAIL'

export const PAGE_GET_SUCCESS = 'PAGE_GET_SUCCESS'
export const PAGE_GET_FAIL = 'PAGE_GET_FAIL'
